### ISSUE TITLE
No ARM Docker image ?

### ISSUE THREAD

**Issue by Write** [wiretrustee/wiretrustee-dashboard#12]
Hi,

It seems there's no ARM build for the Dashboard ? 
https://hub.docker.com/r/wiretrustee/dashboard/tags

`standard_init_linux.go:228: exec user process caused: exec format error`

Thanks !

**Comment by mlsmaycon** [comment]
Hello @Write, thanks for opening the issue. 

We've pushed the changes in PR #13
