### ISSUE TITLE
Add management example for self hosted

### ISSUE THREAD

**Issue by mlsmaycon** [wiretrustee/wiretrustee-dashboard#18]
When users are hosting Wiretrustee themselves, they need to be aware that the custom management URL is needed, otherwise it will point to Wiretrustee cloud services.

**Comment by mlsmaycon** [comment]
see https://github.com/wiretrustee/wiretrustee/issues/246#issuecomment-1060051064 for use case

**Comment by braginini** [comment]
Solved in https://github.com/wiretrustee/wiretrustee-dashboard/pull/20
